### ISSUE TITLE
QT5 Build?

### ISSUE THREAD

**Issue by shadowbq** [hasherezade/ViDi#1]
Any plans to support?

Qt5 SDK
Qt5 Core

**Comment by hasherezade** [comment]
Yes, I was thinking to start developing ViDi again, and as a first step, switching it to Qt5. But I must admit this project is on a low priority for me right now (I just have other projects that I consider more important). It may change depending on how many people will need it.

**Comment by hasherezade** [comment]
Hi! I refactored it, now it can be built with Qt5

**Comment by hasherezade** [comment]
and new builds are available:
https://github.com/hasherezade/ViDi/releases/tag/0.2.5.4
please check them out and let me know if everything is fine!

**Comment by shadowbq** [comment]
Qt_5.11 required not just 5.x FYI

**Comment by hasherezade** [comment]
what exactly do you mean? if you build from the source, the project should build fine with any Qt 5.x.
but in the Linux build that I prepared, indeed I used Qt_5.11. do you mean that build it does not run with a lower version? or something else?

**Comment by shadowbq** [comment]
Yeah I had 5.9 installed on my linux build when using the prebuild distro
```
./ViDi: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11' not found (required by ./ViDi)
```

ldd on ViDi
```
	linux-vdso.so.1 (0x00007ffd4d6df000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007feec88ad000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007feec8144000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007feec79f9000)
[...]
```

```
$> file /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: symbolic link to libQt5Core.so.5.9.5
```

**Comment by hasherezade** [comment]
ok, I see. I will add those libs to the package.

**Comment by hasherezade** [comment]
added - please let me know if it solves the problem.

**Comment by shadowbq** [comment]
Please see: http://doc.qt.io/qt-5/linux-deployment.html#static-linking

**Comment by hasherezade** [comment]
as far as I remember, it is not allowed to link Qt statically if you use non-commercial version. this is why I don't do it.

**Comment by shadowbq** [comment]
From my non-legal dont hold me to the fire.. view

Read https://www.qt.io/faq/ Section 3.7 

**3.7. What are my obligations when using Qt under the LGPL?**

"The user of your application has to be able to re-link your application against a different or modified version of the Qt library. With LGPLv3 it is also explicitly stated that the user needs to be able to run the re-linked binary on it’s intended target device. It is your obligation to provide the user with all necessary tools to enable this process. For embedded devices, this includes making the full toolchain used to compile the library available to users. For parts licensed under LGPLv3 you are obliged to provide full instructions on how to install the modified library on the target device (this is not clearly stated with LGPLv2.1, although running the application against the modified version of the library clearly is the stated intention of the license)"

** You are distributing the source so there is no issue, as someone can relink to another version is necessary. **

**Comment by shadowbq** [comment]
Which ever.. I can always recompile. Thanks for the effort

**Comment by hasherezade** [comment]
yeah, I know that in case of open source projects it can be linked statically too, under some circumstances, but I have to research more about the compliance.
for now I can just add to the CMake an option of static linking, so that anyone who needs it, can switch the mode easily.
